### ISSUE TITLE
error on php 8.1

### ISSUE THREAD

**Issue by parsibox** [aVadim483/fast-excel-writer#13]
hi
on php 8.1 we have error

Fatal error: Cannot make static method XMLReader::open() non static in class avadim\FastExcelReader\Reader in 
vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php on line 32

**Comment by albertbrufau** [comment]
I think that this issue goes to https://github.com/aVadim483/fast-excel-reader

> hi on php 8.1 we have error
> 
> Fatal error: Cannot make static method XMLReader::open() non static in class avadim\FastExcelReader\Reader in vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php on line 32
