### ISSUE TITLE
Fill color in MS Office365

### ISSUE THREAD

**Issue by borg1980** [aVadim483/fast-excel-writer#16]
I had a problem with fill color after creating Excel file - when file is opened in Google Spreadsheet everything is OK (header is red). But opening in MS Office 365 gives kind of greyish dots (enclosing screenshot).
![issue](https://user-images.githubusercontent.com/1286508/189336810-a4d03b71-d50d-411a-9988-b3a931c3786b.png)

Style code looks like this:
        $headStyle = [
            'font' => ['style' => 'bold'],
            'fill' => '#f00',
            'text-align' => 'center',
            'vertical-align' => 'center',
            'border' => 'thin',
        ];

**Comment by BageeR30** [comment]
yep, same

**Comment by aVadim483** [comment]
I see, I'll fix today

**Comment by aVadim483** [comment]
Fixed in [v3.1.2](https://github.com/aVadim483/fast-excel-writer/releases/tag/v3.1.2)
