### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by jarrod-colluco** [aVadim483/fast-excel-writer#20]
Please correct me if I'm wrong, but I can't see that comments or conditional styles are built into this library. Is there any plans in place to do so?

**Comment by jarrod-colluco** [comment]
Thanks for the response. Yes, sorry, I meant conditional formatting. 

I understand. Conditional formatting isn't a big concern, just a nice feature to have. Is there currently a way to add a comment to a cell?

**Comment by jarrod-colluco** [comment]
Is there also a way to be able to set the text orientation? For example, we're looking to use this on a project which displays text in a cell vertically rather than horizonitally.

**Comment by aVadim483** [comment]
I'll add a comment, but haven't decided on conditional formatting yet

**Comment by aVadim483** [comment]
> Thanks for the response. Yes, sorry, I meant conditional formatting.
> 
> I understand. Conditional formatting isn't a big concern, just a nice feature to have. Is there currently a way to add a comment to a cell?

There are currently two types of comments in Excel - **comments** and **notes** (see [here](https://support.microsoft.com/en-us/office/the-difference-between-threaded-comments-and-notes-75a51eec-4092-42ab-abf8-7669077b7be3)). I implemented the ability to add **notes**, so method is called ```addNote()```

**Comment by jarrod-colluco** [comment]
That's great @aVadim483 thank you for adding that in!
