### ISSUE TITLE
Note dimensions

### ISSUE THREAD

**Issue by jarrod-colluco** [aVadim483/fast-excel-writer#22]
Hi @aVadim483 

Thanks for your great work on adding notes in. I have noticed that when adding a note, it needs to be escaped correctly, otherwise certain characters may break the spreadsheet.

I wanted to know whether it was possible to define the width/height of the note? I have seen in the `addNote()` function that you set it through the array - is it possible to expose this to the function or at least allow us to override the note array so that we can specify those ourselves?

The notes don't support text-wrapping so when adding a few lines of text, we need to make sure the note width/height is long enough to read.

**Comment by aVadim483** [comment]
I've confirmed your pull request. I refactored your code a bit and added two more parameters: **fill_color** and **show**

https://github.com/aVadim483/fast-excel-writer#adding-notes
