### ISSUE TITLE
Incorrect escaping of character in number format

### ISSUE THREAD

**Issue by nickicastillo** [aVadim483/fast-excel-writer#24]
Hi,

When a character is preceded with an asterisk (*), in number format, shouldn't be escaped. The asterisk means to repeat a character so that the width of the number fills the column, and it takes that character as literal.

[https://support.microsoft.com/en-au/office/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68#ID0EDN](url)

The function that returns the escaped string:
`avadim\FastExcelWriter\Style::numberFormatStandardized`

Hope it helps.

**Comment by aVadim483** [comment]
Numeric formats do not use the asterisk character (*), but the hash symbol (#)

![image](https://github.com/aVadim483/fast-excel-writer/assets/2246758/0d8d5804-f0a8-4e7e-81ec-6e46ba97baf1)

**Comment by aVadim483** [comment]
Oh, sorry, I understand what you mean, you're right, I'll fix it
