### ISSUE TITLE
How to insert image

### ISSUE THREAD

**Issue by SyahrirMbojo** [aVadim483/fast-excel-writer#29]
How to insert image in fast-excel-writer because i didn't see it in the documentation?

**Comment by aVadim483** [comment]
Now there is no such feature. Might be added later

**Comment by SyahrirMbojo** [comment]
In my opinion, this feature should also exist because there is a possibility that the report will contain a logo image or something else. I hope the feature is available soon because I love using this library because it's simple to use but nice and fast. I need this library because I have a lot of report data that I want to export to excel. Thank you for the help.

**Comment by aVadim483** [comment]
ok, i understand, i'll explore this feature

**Comment by aVadim483** [comment]
I have added this in the version 4.4.0
https://github.com/aVadim483/fast-excel-writer#adding-images

**Comment by SyahrirMbojo** [comment]
Thank you very much and I will try it right away

**Comment by SyahrirMbojo** [comment]
I tried to insert an image and got an error like this

Image file "http://localhost:8081/img/img_petugas_aktif.png" does not exist

<img width="1290" alt="image" src="https://github.com/aVadim483/fast-excel-writer/assets/29540867/5fe3b344-3c54-4947-a08c-5d910b1b31f5">

**Comment by SyahrirMbojo** [comment]
This is my code

<img width="812" alt="image" src="https://github.com/aVadim483/fast-excel-writer/assets/29540867/71b0405d-75b6-474e-9d89-1fda83d0a2ba">

**Comment by aVadim483** [comment]
> Image file "http://localhost:8081/img/img_petugas_aktif.png" does not exist

Use local path to image, not URL

**Comment by SyahrirMbojo** [comment]
In the example above, I tried the local path and it didn't work, I got the error doesn't exist and I need an image with a URL too

**Comment by aVadim483** [comment]
http://localhost:8081/img/img_petugas_aktif.png - it's a local URL, not local path on your drive
the function base_url() obviously also returns a URL

**Comment by SyahrirMbojo** [comment]
but what I want is the URL image from our server and that is what is often needed

**Comment by aVadim483** [comment]
Well, I'll add this future too (I didn't think it was necessary)

**Comment by SyahrirMbojo** [comment]
Thank you for the help

**Comment by aVadim483** [comment]
> but what I want is the URL image from our server and that is what is often needed

added in v4.4.1
