### ISSUE TITLE
padding + min-width

### ISSUE THREAD

**Issue by parsibox** [aVadim483/fast-excel-writer#32]
hi
how can set padding?
how can set min-width with auto width options?

**Comment by aVadim483** [comment]
this will be in future versions

**Comment by aVadim483** [comment]
See in v4.6.x
1. https://github.com/aVadim483/fast-excel-writer/blob/master/docs/02-sheets.md#page-settings
2. https://github.com/aVadim483/fast-excel-writer/tree/master#columns-settings

**Comment by parsibox** [comment]
thanks
