### ISSUE TITLE
Enhancement: ability to specify "activeCell"...

### ISSUE THREAD

**Issue by AzzaAzza69** [aVadim483/fast-excel-writer#33]
In the case of a graphic inserted in "A1" that takes up (height wise) approx 4 rows, I would like to set the activeCell to "A5".

**Comment by aVadim483** [comment]
in v.4.7 https://github.com/aVadim483/fast-excel-writer/blob/master/docs/02-sheets.md#setting-active-cells

**Comment by AzzaAzza69** [comment]
Great work, but it appears that the setActiveCell only works if not freezing any row/col.

**Comment by AzzaAzza69** [comment]
If I open the sheet (with a frozen row) in Excel, select P40 and save and re-open, P40 is brought into view and is still active.

**Comment by aVadim483** [comment]
> Great work, but it appears that the setActiveCell only works if not freezing any row/col.

fixed in v4.7.1
