### ISSUE TITLE
Template File?

### ISSUE THREAD

**Issue by atmanegara** [aVadim483/fast-excel-writer#36]
write using excel templates?

**Comment by aVadim483** [comment]
Not yet, it always generates a new Excel file

**Comment by atmanegara** [comment]
> Not yet, it always generates a new Excel file

I like your library,
I hope there will be support for template files, I have a problem with phpspreadsheet which cannot display trillion numbers with 2 decimal places which are always rounded, I have tried your library with trillions, it is very good according to my expectations, ok, thanks, good luck u

**Comment by aVadim483** [comment]
@atmanegara
https://github.com/aVadim483/fast-excel-templator
