### ISSUE TITLE
Save File when cell value has formula

### ISSUE THREAD

**Issue by lvlightvivian** [aVadim483/fast-excel-writer#37]
Hi I try to export a formula sheet and upload to googlesheets.
but formula cell not works correctly. It just show formula string, not formula execute result.

so I unziped xlsx, found sheet.xml. the formula cell value like this:
&lt;c r="C4" s="0"&gt;&lt;f&gt;=SUM(C1:C3)&lt;/f&gt;&lt;/c&gt;

and I try to check other xlsx file download from googlesheets
&lt;c r="B4" s="2"&gt;&lt;f t="shared" ref="B4:C4" si="2"&gt;SUM(B1:B3)&lt;/f&gt;&lt;v&gt;2004&lt;/v&gt;&lt;/c&gt;
I found the formula cell value not contain '=' on first char

I modified Writer.php Line 996 to remove '='
$file->write('<c r="' . $cellName . '" s="' . $cellStyleIdx . '"><f>' . mb_substr(self::xmlSpecialChars($value), 1) . '</f></c>');
and It works fine

thank you

**Comment by aVadim483** [comment]
Thanx for report, I'll check this
