### ISSUE TITLE
How to merged cells ?

### ISSUE THREAD

**Issue by insiderinside** [aVadim483/fast-excel-writer#4]
i see all demo but not see option for merged cell ?

**Comment by insiderinside** [comment]
"title": "ErrorException",
    "type": "ErrorException",
    "code": 500,
    "message": "tempnam(): file created in the system's temporary directory",
    "file": "-----avadim/fast-excel-writer/src/FastExcelWriter/Writer.php",
    "line": 123,

**Comment by aVadim483** [comment]
> i see all demo but not see option for merged cell ?

See demo/demo-07-advanced.php
```
$area->setValue('A2', 'text'); // write text to single cell A2
$area->setValue('A2:B2', 'text'); // write text to merged cells A2:B2
```
```

**Comment by aVadim483** [comment]
> "title": "ErrorException",
> "type": "ErrorException",
> "code": 500,
> "message": "tempnam(): file created in the system's temporary directory",
> "file": "-----avadim/fast-excel-writer/src/FastExcelWriter/Writer.php",
> "line": 123,

See "Other Options" in README.md
```
use \avadim\FastExcelWriter\Excel;

Excel::setTempDir('/path/to/temp/dir'); // use this call before Excel::create()
$excel = Excel::create();

// Or alternative variant

$excel = Excel::create('SheetName', ['temp_dir' => '/path/to/temp/dir']);
```
