### ISSUE TITLE
How to write a formula

### ISSUE THREAD

**Issue by s-alexsan** [aVadim483/fast-excel-writer#41]
I have a model that have a formula <code>'=PROCV(E4;'EFETIVO ATUALIZADO'!$B:$D;2;FALSO)'</code>
In the library I was using this way <code>$fomulaTest = "=PROCV(RC[-1];'EFETIVO ATUALIZADO'!\$B:\$D;2;FALSO)";</code>

And don't work, how to write a formula in this case?

**Comment by aVadim483** [comment]
I think PROCV is the name of the function in Portuguese. You can use the original English function names without any problems. But if you use names in some other language, then the library must detect this language. It tries to do this automatically, but sometimes it does it wrong. Then you need to specify the locale explicitly:
```php
$excel = Excel::create();
$excel->setLocale('pt');
```
But you need use version 4.8 or higher
