### ISSUE TITLE
4.81 not work

### ISSUE THREAD

**Issue by lollita** [aVadim483/fast-excel-writer#42]
4.81 not work I have to switch to previous.

> <br />
> <b>Fatal error</b>:  Uncaught Error: Class &quot;avadim\FastExcelHelper\Helper&quot; not found in c:\test\FastExcelWriter\FastExcelWriter\Excel.php:586
> Stack trace:
> #0 c:\test\FastExcelWriter\FastExcelWriter\Excel.php(824): avadim\FastExcelWriter\Excel::colNumber('A')
> #1 c:\test\FastExcelWriter\FastExcelWriter\Excel.php(925): avadim\FastExcelWriter\Excel::rangeDimensionRelative('A1', NULL, true)
> #2 c:\test\FastExcelWriter\FastExcelWriter\Sheet.php(2231): avadim\FastExcelWriter\Excel::rangeDimension('A1', true)
> #3 c:\test\FastExcelWriter\FastExcelWriter\Sheet.php(2199): avadim\FastExcelWriter\Sheet-&gt;_rangeDimension('A1')
> #4 c:\test\FastExcelWriter\FastExcelWriter\Sheet.php(2266): avadim\FastExcelWriter\Sheet-&gt;_parseAddress('A1')
> #5 c:\test\FastExcelWriter\FastExcelWriter\Sheet.php(199): avadim\FastExcelWriter\Sheet-&gt;_setCellData('A1', NULL, NULL, false)
> #6 c:\test\FastExcelWriter\FastExcelWriter\Excel.php(247): avadim\FastExcelWriter\Sheet-&gt;__construct('Alfa')
> #7 c:\test\FastExcelWriter\FastExcelWriter\Excel.php(1054): avadim\FastExcelWriter\Excel::createSheet('Alfa')
> #8 c:\test\FastExcelWriter\FastExcelWriter\Excel.php(226): avadim\FastExcelWriter\Excel-&gt;makeSheet('Alfa')
> #9 c:\test\calc.php(749): avadim\FastExcelWriter\Excel::create(Array)
>

**Comment by aVadim483** [comment]
You need to update with composer for the dependencies to install
