### ISSUE TITLE
How to set Hyperlink using writeRow

### ISSUE THREAD

**Issue by shulogsm** [aVadim483/fast-excel-writer#43]
When i try to add options to an array to set a hyperlink for a cell, it shows only an empty cell:

This is how i´m trying to do:

$array_cells = array();
$array_cells[] = $name;
$array_cells[] = $company;
$array_cells[] = $otheroptions;
...
    **$Link = [$value, ['hyperlink' => true]];**
$array_cells[] = $Link;
$sheet->writeRow($array_cells, $rowOptions, $cellsStyle);

What is the correct way to set an hyperlink using writeRow option?

Thanks for your great work!

**Comment by aVadim483** [comment]
The first argument is a value array, the 2nd - row styles, the 3rd - styles of specified cells in the row

```php
$rowValues = [
    'text',
    'http://google.com',
    123456,
];
$rowStyle = [];
$cellStyles = [
    [], // style for the first cell,
    ['hyperlink' => true], // 2nd cell
    [], // 3rd cell
];

$sheet->writeRow($rowValues, $rowStyle, $cellStyles);

```

Other way
```php
$cellStyles = [
    'B' => ['hyperlink' => true],
];
$sheet->writeRow($rowValues, [], $cellStyles);
```

**Comment by shulogsm** [comment]
Great! Second option is better for me! Thank you very much!!
