### ISSUE TITLE
set Date format in Locale Settings

### ISSUE THREAD

**Issue by lollita** [aVadim483/fast-excel-writer#44]
I have to get the date format as:
DD/MM/YYYY
It work in Windows server but not in Linux server where it become:
YYYY/MM/DD
I tryed to force with 
```
$excel->style->setLocaleSettings([
      'formats' => [
          '@DATE' => 'DD-MM-YYYY',
          '@TIME' => 'HH:MM:SS',
          '@DATETIME' => 'DD-MM-YYYY HH:MM:SS',
          '@MONEY' => '# ##0,00',
      ],
  ]
);

```
And it works.
Do it is the right via?

**Comment by aVadim483** [comment]
Yes, this is one of the working ways
