### ISSUE TITLE
Set Default Font is used only for written cells

### ISSUE THREAD

**Issue by guidobonuzzi** [aVadim483/fast-excel-writer#45]
This is an example:
```
$excel = Excel::create(
    [
        'test',
    ],
)
    ->setDefaultStyle([Style::FONT => [Style::FONT_NAME => 'Calibri', Style::FONT_SIZE => 11]]);

$sheet = $excel->sheet(1);

$sheet->writeCell('TEST');
```

The Excel file has the right font only in cell A1, in the rest of the file Arial 10 is used.

If this is intended to guarantee high performance, I still think it is better to change the font from Arial 10 to Calibri 11 which seems to be the current Excel standard.

Thanks

**Comment by aVadim483** [comment]
fixed in v4.10.0
