### ISSUE TITLE
QUESTION: Append to existing file

### ISSUE THREAD

**Issue by lrakauskas** [aVadim483/fast-excel-writer#47]
How would you go about opening existing XLSX and appending data to it? Is there some sort of option when calling `Excel::create()` to actually open an existing file rather than starting a fresh one?

In a nutshell, I have a job that writes few lines into XLSX file and what I would like to do is to save that file and later come back to it on a different job and append more rows to the very same file. Is there a functionality to write to an existing file?

**Comment by aVadim483** [comment]
Now yes you can do it - https://github.com/aVadim483/fast-excel-templator

**Comment by Raman117** [comment]
@aVadim483  how can i do this but with image

like using templater i want to add image in sheet 5, row maybe a7
i see that its in the writter package
anyway i can use that in template?

**Comment by aVadim483** [comment]
@Raman117 not yet, now only images from the template are transferred to the output file
but I plan to do this in future versions
