### ISSUE TITLE
Little issue

### ISSUE THREAD

**Issue by ade585** [aVadim483/fast-excel-writer#5]
Work fine and fast ;o)

Good job.

One remarks : when writing 'hello world ' the produced file contains 'hello world'. 

Meaning that the last space character is removed. 

Can it be solved ?

**Comment by aVadim483** [comment]
Fixed

**Comment by ade585** [comment]
Hi, little type error 

Fatal error: Uncaught Error: Call to undefined method avadim\FastExcelWriter\Sheet::wtiteHeader() in C:\Program Files\NetMake\v9-

**Comment by ade585** [comment]
works thx you so much
