### ISSUE TITLE
Output Error

### ISSUE THREAD

**Issue by BaddyM** [aVadim483/fast-excel-writer#50]
I have this error that appears after the sheet is generated, how can i go about it?
I am using version 4.11.0
![Screenshot from 2024-02-12 20-50-22](https://github.com/aVadim483/fast-excel-writer/assets/101480645/e7f09296-4ce8-4d78-b47e-e0983e685020)

**Comment by aVadim483** [comment]
There is too little information to understand what the problem is. When do you get this error? When trying to write a file to disk? Or when trying to read a created file?
