### ISSUE TITLE
Fatal error: Uncaught Error: Class "Locale" not found

### ISSUE THREAD

**Issue by patrickteng** [aVadim483/fast-excel-writer#52]
Fatal error: Uncaught Error: Class "Locale" not found in /Applications/XAMPP/xamppfiles/htdocs/project_name/vendor/avadim/fast-excel-writer/src/FastExcelWriter/Excel.php:295

After some fiddling around, I managed to make it work (temp directory was a pain to configure as well, the error message is always using "sys_get_temp_dir()" even when tempDir is overwrite. But nonetheless, it work after. The last error was the above, I managed to make it work by commenting out the lines to set Locale, but is it the intended result or is a file missing?

Thanks

![Screenshot 2024-03-25 at 3 59 48 PM](https://github.com/aVadim483/fast-excel-writer/assets/13133091/16b80ac3-c691-4e39-af54-6320a1a6fcaf)

**Comment by aVadim483** [comment]
Locale is the class from php extension intl, you need enable this extension in php.ini
