### ISSUE TITLE
setColWidthAuto resizer not working 100% effectively

### ISSUE THREAD

**Issue by elidon555** [aVadim483/fast-excel-writer#57]
SetColWidthAuto doesn't work correctly when you also use setAutofilter

```php
$worksheet->writeHeader($headers);
$worksheet->setAutofilter();
$worksheet->setColWidthAuto(self::getColumnRange($headers));
```

Filter applied below:
![image](https://github.com/aVadim483/fast-excel-writer/assets/74297955/c2ae9a60-39d5-4481-a4c9-858275df39bb)
![image](https://github.com/aVadim483/fast-excel-writer/assets/74297955/bafd8d73-2f3d-45ef-ae10-be9d883ee089)
<br>

Filter not applied below: (As u can see last character is not visible)
![image](https://github.com/aVadim483/fast-excel-writer/assets/74297955/c1d2f9b9-b304-4967-b2ee-ac39ec17fc75)
<br>

Desired result below by manually double-clicking between the two columns
![image](https://github.com/aVadim483/fast-excel-writer/assets/74297955/c258aec0-2cad-4e9f-868c-1db07d60d010)
<br>

Is this possible? PHPSpreadsheet does this very well

**Comment by aVadim483** [comment]
Here's an explanation of how PhpSpreadsheet calculates column width: https://github.com/PHPOffice/PhpSpreadsheet/issues/2750

The GD method is definitely not suitable, because it will be very slow on large tables. The FastExcelWriter library is designed to create Excel files very quickly, and cannot use this method. But I will look into PhpSpreadsheet alternative method

**Comment by elidon-staxxer** [comment]
> Here's an explanation of how PhpSpreadsheet calculates column width: [PHPOffice/PhpSpreadsheet#2750](https://github.com/PHPOffice/PhpSpreadsheet/issues/2750)
> 
> The GD method is definitely not suitable, because it will be very slow on large tables. The FastExcelWriter library is designed to create Excel files very quickly, and cannot use this method. But I will look into PhpSpreadsheet alternative method

Ah I see, thank you for the explanation!

**Comment by aVadim483** [comment]
I have improved the column width calculation, please update to 5.3 and check it
