### ISSUE TITLE
Issue with R1C1 absolute references

### ISSUE THREAD

**Issue by zupolgec** [aVadim483/fast-excel-writer#59]
I found out that all R1C1 references are treated as relative references. So "R1C1" which whould be "$A$1" is instead treated as "R[1]C[1]" which means "cell one row below one column to the right"

```
use avadim\FastExcelWriter\Excel;

$excel = Excel::create(['Sheet 1']);
$sheet = $excel->sheet();

$sheet->writeRow([1,2,'=R1C1+R1C2']);
```

Should produce:
| A | B | C |
| - | - | - |
| 1  | 2 | =$A$1+$B$1 |

Instead I get:
| A | B | C |
| - | - | - |
| 1  | 2 | =D2+E2 |

Like if I wrote `=R[1]C[1]+R[1]C[2]`

**Comment by aVadim483** [comment]
Yes, you are right. I'll fix it soon

**Comment by aVadim483** [comment]
fixed in v.5.3
