### ISSUE TITLE
Cell Note background shape issue

### ISSUE THREAD

**Issue by arthur-ebing** [aVadim483/fast-excel-writer#60]
Hi,
I'm using fast-excel-writer to create spreadsheets that include cell notes which are working 100%. When hovering over the cell containing the note it shows perfectly in a yellow rectangle as below:
![image](https://github.com/aVadim483/fast-excel-reader/assets/31281703/d0e75ea6-6312-4390-a38c-e47fd535f5d2)
But when I open the file in Excel, save it, close it and open it again, the note pops up with an arrow instead of a rectangle as follows:
![image](https://github.com/aVadim483/fast-excel-reader/assets/31281703/c5054dab-18d7-4bf2-a59a-86cf1876a068)

Is there anything I need to set to stop that from happening?

Thanks, Arthur

**Comment by aVadim483** [comment]
fixed in v.5.3

**Comment by arthur-ebing** [comment]
Thank you so much!
