### ISSUE TITLE
[SOLVED} creating excel, opening the file always has an error

### ISSUE THREAD

**Issue by atmanegara** [aVadim483/fast-excel-writer#63]
this is my code

![image](https://github.com/aVadim483/fast-excel-writer/assets/9096711/8a3000e5-2384-46c8-8b49-2c86e9d6b722)

The file was successfully created and I opened it using MS Office (Excel)
![image](https://github.com/aVadim483/fast-excel-writer/assets/9096711/f97d5fd3-e6ba-4ae5-a33b-34b3604978eb)

![image](https://github.com/aVadim483/fast-excel-writer/assets/9096711/241104e8-b8f7-4f72-a219-4f6a400c3b4f)

--edit
**[solved]**
change file .../FastExcelWriter/Excel.php
in the download function, after readfile($tempFile) add the following code

 unlink($tmpFile);
exit;

Ok

**Comment by Guzhven** [comment]
unlink($tmpFile); was added.
But why wasn't **exit;** added? After including exit, the error related to the file disappears when using the library on Windows.
