### ISSUE TITLE
Autoloader not using correct directory separators

### ISSUE THREAD

**Issue by SwcIt** [aVadim483/fast-excel-writer#7]
Hi,
When using the autoloader it does not correctly create a path to the php file.

Line 6: 
`include __DIR__ . '/FastExcelWriter/' . str_replace($namespace, '/', $class) . '.php';`

The '\\\\' (or '\\' if you will) in the $class is not converted to a '/' and results in an error on my linux machine, (notice the last directory seperator):
`PHP Warning:  include(...path.../FastExcelWriter//Exception\\SaveException.php): failed to open stream: No such file or directory in ...path.../autoload.php on line 6`

I've fixed this by adding another replace which converts the '\\' into '/' and then it works fine.

The issue seems also present in the fast-excel-reader.

**Comment by aVadim483** [comment]
fixed
