### ISSUE TITLE
Rich text problem

### ISSUE THREAD

**Issue by kouroshfar** [aVadim483/fast-excel-writer#74]
Hi. Thanks for your great library.
I have a problem about using rich text
as you mentioned on this line of documents (https://github.com/aVadim483/fast-excel-writer/blob/master/docs/03-writing.md#using-rich-text) when i want to have rich text, i have 2 ways to do it
my problem is when i put it bold on a word, next words will be bold until a new tag
![Untitled](https://github.com/user-attachments/assets/ab74c724-c6cd-4bf5-b309-e51ebd7755dc)
and it's different from what did you do
![rich-text](https://github.com/user-attachments/assets/09798647-31d5-48de-a0aa-8d8cb9770da5)

i tried in both ways and there isn't different on the result.
can you help me?

**Comment by aVadim483** [comment]
Я использовал этот код
```php
$excel = \avadim\FastExcelWriter\Excel::create();
$sheet = $excel->sheet();

$richText = new \avadim\FastExcelWriter\RichText();
$richText->addText('ATTENTION!')->setBold();
$richText->addText(' The product is reserved for ');
$richText->addText('5 days')->setUnderline()->setColor('#f00');

//$sheet->writeCell($richText);
$sheet->writeTo('B2', $richText);
//$sheet->writeRow(['plain text', $richText]);

$richText = new \avadim\FastExcelWriter\RichText('<b>ATTENTION!</b> The product is reserved for <u><c="#f00">5 days</c></u>');
$sheet->writeTo('B5', $richText);

$excel->save(__DIR__ . '/rich_text.xlsx');
```

и получил этот результат

![image](https://github.com/user-attachments/assets/a117a5d6-5c28-4901-a92b-d070c18cba4b)

**Comment by aVadim483** [comment]
I don't understand what your problem is.
