### ISSUE TITLE
PHP 8.3 compatibility

### ISSUE THREAD

**Issue by GuidoPX** [aVadim483/fast-excel-writer#75]
Hi,

could you please update line 251 in Sheet.php to make it compatible with PHP 8.3?
In PHP 8.3, calling **get_class** function without parameters is deprecated.
https://php.watch/versions/8.3/get_class-get_parent_class-parameterless-deprecated

Solution is easy:
Just replace get_class() with __CLASS__

Thank you very much.

**Comment by aVadim483** [comment]
fixed
