### ISSUE TITLE
"Found unconstructed IntlDateFormatter"

### ISSUE THREAD

**Issue by k-risc** [aVadim483/fast-excel-writer#77]
`Excel::setDefaultLocale()` calls `Excel::setLocale()` for any locale that does not equal "C" and has a strlen greater than 1.

On my developer machine I have a locale "C.UTF-8" which then causes the error in `Excel::setLocale()`.

Would it be feasible to not only ignore locale "C", but also "C.UTF-8"?

**Comment by aVadim483** [comment]
I tried to reproduce the problem, but I couldn't, everything works correctly for me with the locale "C.UTF-8"
And Excel::setDefaultLocale() always calls Excel::setLocale()

What version of the library are you using?

**Comment by k-risc** [comment]
It was v2.3.10. We are working on getting all clients on PHP 8.1, but at the moment we needed to stick to PHP 7.3. I changed the composer settings to use PHP 7.4, then v5.8.1 of fast-excel-write got installed, and the problem disappeared. Thanks for your response.
