### ISSUE TITLE
Create Excel from an existing one

### ISSUE THREAD

**Issue by marcoas** [aVadim483/fast-excel-writer#80]
(Translated by Google)

Is it possible to create a new Excel spreadsheet from 3 pre-existing .xlsx files?

I need each of the existing files (which always have only one sheet) to become a sheet in the new file.

**Comment by aVadim483** [comment]
I understand - you want to merge sheets from different files into one file. This library does not work with existing files, it creates new ones. But the functionality you need will soon appear in another library - https://github.com/aVadim483/fast-excel-templator
