### ISSUE TITLE
Are there any plans to support data validation, conditional styling, or row/column visibility?

### ISSUE THREAD

**Issue by PaulCombal** [aVadim483/fast-excel-writer#81]
Will these features be supported? Is there any roadmap?

**Comment by aVadim483** [comment]
Support for data validation and conditional styling is not planned yet
The library now supports visibility
```php
// Hide row 8
$sheet->setRowVisible(8, false);

// Other way
$sheet->setRowHidden(8);

// Hide rows 9, 10, 11
$sheet->setRowVisible([9, 10, 11], false);

// Show row 10
$sheet->setRowVisible(10, true);

// Hide column B
$sheet->setColVisible('B', false);

// Other way
$sheet->setColHidden('B');

// Hide columns B, E, H
$sheet->setColVisible(['B', 'E', 'H'], false);

// Show column E
$sheet->setColVisible('E', true);
```

**Comment by PaulCombal** [comment]
My bad, I'm sorry for missing the visiblle part in the documentation.

Conditional styling is not an absolute priority in the project I'm working in, however data validation is. The objective is to make a "Dropdown list" choice of possibilities (like #65). Therefore I would be very excited if this feature were available.

I'm not an expert in SpreadsheetML, but to my understanding adding data validation tags would not cause a slowdown in writing speed since it consists of a tag per data validation sqref.

I understand you have other priorities but I just wanted to express my criteria for the selection of the library, and to thank you for your amazing work and dedication :heart:

**Comment by aVadim483** [comment]
As for the "dropdown list", I plan to implement this feature, but I can't give a deadline

**Comment by aVadim483** [comment]
Data validation was relised in version 6
