### ISSUE TITLE
Is there an API reference?

### ISSUE THREAD

**Issue by PaulCombal** [aVadim483/fast-excel-writer#84]
Hello again,

The Readme files are very helpful, is there an API reference somewhere indicating what are the possible options to pass to every method?

For example, I don't think the options passed to `Sheet::nextRow` are documented.

Thank you!

**Comment by aVadim483** [comment]
I have been meaning to do proper documentation for a long time, but I didn't have enough time.

**Comment by aVadim483** [comment]
Now there is the [API Reference](https://github.com/aVadim483/fast-excel-writer/blob/master/docs/90-api-reference.md), not very high quality, but there is one

**Comment by PaulCombal** [comment]
It's already very good! If there is something unclear I will make sure to let you know. 

In the past I've used tools like [phpdocumentor](https://phpdoc.org/) that generate your documentation in one command, and you can host it on github pages. It's not much but I feel it's an argument to show how production-ready the tool is.

Once again thank you, this is already way enough for my use case <3
