### ISSUE TITLE
Disabling message box on data validation

### ISSUE THREAD

**Issue by PaulCombal** [aVadim483/fast-excel-writer#86]
Hello,

When using data validation, there is an optional option in Excel that lets you show a popup when the data is invalid. This popup can be disabled in the user interface as shown (LibreOffice and Excel have the same):

![image](https://github.com/user-attachments/assets/3ae9519f-7e50-46a2-93c7-4380f789a623)

So far I haven't seen the possibility to control this option. As an example example, is it possible to make a validation dropbox with no error message if the value isn't in the list?

Is there something I missed?

Once again thank you!

**Comment by aVadim483** [comment]
I forgot, this was already implemented )
```php
// Disallow error message
$validation->showErrorMessage(false);

```

**Comment by PaulCombal** [comment]
That's just perfect, one step ahaead as always. Many thanks!
